//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.DynamicIP
{
    using System;
    using System.Collections.Generic;
    
    public partial class vpn_Register
    {
        public string KEY { get; set; }
        public string Name { get; set; }
        public string vpnID { get; set; }
        public string vpnPW { get; set; }
        public string vpnIP { get; set; }
        public string vpnEncryptionType { get; set; }
        public System.DateTime createDate { get; set; }
        public Nullable<System.DateTime> modifyDate { get; set; }
        public Nullable<bool> enable { get; set; }
        public int autoid { get; set; }
        public string vpnMac { get; set; }
    }
}
