//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace CallInfo
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class AppDataPhoneEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“AppDataPhoneEntities”部分中的连接字符串初始化新 AppDataPhoneEntities 对象。
        /// </summary>
        public AppDataPhoneEntities() : base("name=AppDataPhoneEntities", "AppDataPhoneEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 AppDataPhoneEntities 对象。
        /// </summary>
        public AppDataPhoneEntities(string connectionString) : base(connectionString, "AppDataPhoneEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 AppDataPhoneEntities 对象。
        /// </summary>
        public AppDataPhoneEntities(EntityConnection connection) : base(connection, "AppDataPhoneEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Phone_CallContent> Phone_CallContent
        {
            get
            {
                if ((_Phone_CallContent == null))
                {
                    _Phone_CallContent = base.CreateObjectSet<Phone_CallContent>("Phone_CallContent");
                }
                return _Phone_CallContent;
            }
        }
        private ObjectSet<Phone_CallContent> _Phone_CallContent;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Phone_ContectClass> Phone_ContectClass
        {
            get
            {
                if ((_Phone_ContectClass == null))
                {
                    _Phone_ContectClass = base.CreateObjectSet<Phone_ContectClass>("Phone_ContectClass");
                }
                return _Phone_ContectClass;
            }
        }
        private ObjectSet<Phone_ContectClass> _Phone_ContectClass;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Phone_Records> Phone_Records
        {
            get
            {
                if ((_Phone_Records == null))
                {
                    _Phone_Records = base.CreateObjectSet<Phone_Records>("Phone_Records");
                }
                return _Phone_Records;
            }
        }
        private ObjectSet<Phone_Records> _Phone_Records;

        #endregion
        #region AddTo 方法
    
        /// <summary>
        /// 用于向 Phone_CallContent EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToPhone_CallContent(Phone_CallContent phone_CallContent)
        {
            base.AddObject("Phone_CallContent", phone_CallContent);
        }
    
        /// <summary>
        /// 用于向 Phone_ContectClass EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToPhone_ContectClass(Phone_ContectClass phone_ContectClass)
        {
            base.AddObject("Phone_ContectClass", phone_ContectClass);
        }
    
        /// <summary>
        /// 用于向 Phone_Records EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToPhone_Records(Phone_Records phone_Records)
        {
            base.AddObject("Phone_Records", phone_Records);
        }

        #endregion
    }
    

    #endregion
    
    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AppDataPhoneModel", Name="Phone_CallContent")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Phone_CallContent : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Phone_CallContent 对象。
        /// </summary>
        /// <param name="autoid">autoid 属性的初始值。</param>
        public static Phone_CallContent CreatePhone_CallContent(global::System.Int32 autoid)
        {
            Phone_CallContent phone_CallContent = new Phone_CallContent();
            phone_CallContent.autoid = autoid;
            return phone_CallContent;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 autoid
        {
            get
            {
                return _autoid;
            }
            set
            {
                if (_autoid != value)
                {
                    OnautoidChanging(value);
                    ReportPropertyChanging("autoid");
                    _autoid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("autoid");
                    OnautoidChanged();
                }
            }
        }
        private global::System.Int32 _autoid;
        partial void OnautoidChanging(global::System.Int32 value);
        partial void OnautoidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ID
        {
            get
            {
                return _ID;
            }
            set
            {
                OnIDChanging(value);
                ReportPropertyChanging("ID");
                _ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID");
                OnIDChanged();
            }
        }
        private Nullable<global::System.Int32> _ID;
        partial void OnIDChanging(Nullable<global::System.Int32> value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> contectClass
        {
            get
            {
                return _contectClass;
            }
            set
            {
                OncontectClassChanging(value);
                ReportPropertyChanging("contectClass");
                _contectClass = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("contectClass");
                OncontectClassChanged();
            }
        }
        private Nullable<global::System.Int32> _contectClass;
        partial void OncontectClassChanging(Nullable<global::System.Int32> value);
        partial void OncontectClassChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String contectText
        {
            get
            {
                return _contectText;
            }
            set
            {
                OncontectTextChanging(value);
                ReportPropertyChanging("contectText");
                _contectText = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("contectText");
                OncontectTextChanged();
            }
        }
        private global::System.String _contectText;
        partial void OncontectTextChanging(global::System.String value);
        partial void OncontectTextChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AppDataPhoneModel", Name="Phone_ContectClass")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Phone_ContectClass : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Phone_ContectClass 对象。
        /// </summary>
        /// <param name="clsID">clsID 属性的初始值。</param>
        public static Phone_ContectClass CreatePhone_ContectClass(global::System.Int32 clsID)
        {
            Phone_ContectClass phone_ContectClass = new Phone_ContectClass();
            phone_ContectClass.clsID = clsID;
            return phone_ContectClass;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 clsID
        {
            get
            {
                return _clsID;
            }
            set
            {
                if (_clsID != value)
                {
                    OnclsIDChanging(value);
                    ReportPropertyChanging("clsID");
                    _clsID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("clsID");
                    OnclsIDChanged();
                }
            }
        }
        private global::System.Int32 _clsID;
        partial void OnclsIDChanging(global::System.Int32 value);
        partial void OnclsIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String clsName
        {
            get
            {
                return _clsName;
            }
            set
            {
                OnclsNameChanging(value);
                ReportPropertyChanging("clsName");
                _clsName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("clsName");
                OnclsNameChanged();
            }
        }
        private global::System.String _clsName;
        partial void OnclsNameChanging(global::System.String value);
        partial void OnclsNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String clsDescription
        {
            get
            {
                return _clsDescription;
            }
            set
            {
                OnclsDescriptionChanging(value);
                ReportPropertyChanging("clsDescription");
                _clsDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("clsDescription");
                OnclsDescriptionChanged();
            }
        }
        private global::System.String _clsDescription;
        partial void OnclsDescriptionChanging(global::System.String value);
        partial void OnclsDescriptionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AppDataPhoneModel", Name="Phone_Records")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Phone_Records : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Phone_Records 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        public static Phone_Records CreatePhone_Records(global::System.Int32 id)
        {
            Phone_Records phone_Records = new Phone_Records();
            phone_Records.ID = id;
            return phone_Records;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dwCode
        {
            get
            {
                return _dwCode;
            }
            set
            {
                OndwCodeChanging(value);
                ReportPropertyChanging("dwCode");
                _dwCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dwCode");
                OndwCodeChanged();
            }
        }
        private global::System.String _dwCode;
        partial void OndwCodeChanging(global::System.String value);
        partial void OndwCodeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dwName
        {
            get
            {
                return _dwName;
            }
            set
            {
                OndwNameChanging(value);
                ReportPropertyChanging("dwName");
                _dwName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dwName");
                OndwNameChanged();
            }
        }
        private global::System.String _dwName;
        partial void OndwNameChanging(global::System.String value);
        partial void OndwNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dwContact
        {
            get
            {
                return _dwContact;
            }
            set
            {
                OndwContactChanging(value);
                ReportPropertyChanging("dwContact");
                _dwContact = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dwContact");
                OndwContactChanged();
            }
        }
        private global::System.String _dwContact;
        partial void OndwContactChanging(global::System.String value);
        partial void OndwContactChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String callPhone
        {
            get
            {
                return _callPhone;
            }
            set
            {
                OncallPhoneChanging(value);
                ReportPropertyChanging("callPhone");
                _callPhone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("callPhone");
                OncallPhoneChanged();
            }
        }
        private global::System.String _callPhone;
        partial void OncallPhoneChanging(global::System.String value);
        partial void OncallPhoneChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> callInOut
        {
            get
            {
                return _callInOut;
            }
            set
            {
                OncallInOutChanging(value);
                ReportPropertyChanging("callInOut");
                _callInOut = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("callInOut");
                OncallInOutChanged();
            }
        }
        private Nullable<global::System.Boolean> _callInOut;
        partial void OncallInOutChanging(Nullable<global::System.Boolean> value);
        partial void OncallInOutChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> callDate
        {
            get
            {
                return _callDate;
            }
            set
            {
                OncallDateChanging(value);
                ReportPropertyChanging("callDate");
                _callDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("callDate");
                OncallDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _callDate;
        partial void OncallDateChanging(Nullable<global::System.DateTime> value);
        partial void OncallDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String callContent
        {
            get
            {
                return _callContent;
            }
            set
            {
                OncallContentChanging(value);
                ReportPropertyChanging("callContent");
                _callContent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("callContent");
                OncallContentChanged();
            }
        }
        private global::System.String _callContent;
        partial void OncallContentChanging(global::System.String value);
        partial void OncallContentChanged();

        #endregion
    
    }

    #endregion
    
}
