//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace HWATT
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class HWATTEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“HWATTEntities”部分中的连接字符串初始化新 HWATTEntities 对象。
        /// </summary>
        public HWATTEntities() : base("name=HWATTEntities", "HWATTEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 HWATTEntities 对象。
        /// </summary>
        public HWATTEntities(string connectionString) : base(connectionString, "HWATTEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 HWATTEntities 对象。
        /// </summary>
        public HWATTEntities(EntityConnection connection) : base(connection, "HWATTEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<KQZ_Card> KQZ_Card
        {
            get
            {
                if ((_KQZ_Card == null))
                {
                    _KQZ_Card = base.CreateObjectSet<KQZ_Card>("KQZ_Card");
                }
                return _KQZ_Card;
            }
        }
        private ObjectSet<KQZ_Card> _KQZ_Card;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<KQZ_Employee> KQZ_Employee
        {
            get
            {
                if ((_KQZ_Employee == null))
                {
                    _KQZ_Employee = base.CreateObjectSet<KQZ_Employee>("KQZ_Employee");
                }
                return _KQZ_Employee;
            }
        }
        private ObjectSet<KQZ_Employee> _KQZ_Employee;

        #endregion
        #region AddTo 方法
    
        /// <summary>
        /// 用于向 KQZ_Card EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToKQZ_Card(KQZ_Card kQZ_Card)
        {
            base.AddObject("KQZ_Card", kQZ_Card);
        }
    
        /// <summary>
        /// 用于向 KQZ_Employee EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToKQZ_Employee(KQZ_Employee kQZ_Employee)
        {
            base.AddObject("KQZ_Employee", kQZ_Employee);
        }

        #endregion
    }
    

    #endregion
    
    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HWATTModel", Name="KQZ_Card")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class KQZ_Card : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 KQZ_Card 对象。
        /// </summary>
        /// <param name="cardID">CardID 属性的初始值。</param>
        /// <param name="employeeID">EmployeeID 属性的初始值。</param>
        /// <param name="cardTime">CardTime 属性的初始值。</param>
        /// <param name="cardTypeID">CardTypeID 属性的初始值。</param>
        /// <param name="devID">DevID 属性的初始值。</param>
        /// <param name="devClass">DevClass 属性的初始值。</param>
        /// <param name="imgID">ImgID 属性的初始值。</param>
        /// <param name="imgStatus">ImgStatus 属性的初始值。</param>
        /// <param name="isValidate">IsValidate 属性的初始值。</param>
        /// <param name="faceIDNo">FaceIDNo 属性的初始值。</param>
        /// <param name="modifyUser">ModifyUser 属性的初始值。</param>
        /// <param name="modifyType">ModifyType 属性的初始值。</param>
        public static KQZ_Card CreateKQZ_Card(global::System.Int64 cardID, global::System.Int64 employeeID, global::System.DateTime cardTime, global::System.Int16 cardTypeID, global::System.Int64 devID, global::System.Int16 devClass, global::System.Int64 imgID, global::System.Int16 imgStatus, global::System.Int16 isValidate, global::System.String faceIDNo, global::System.Int32 modifyUser, global::System.Int16 modifyType)
        {
            KQZ_Card kQZ_Card = new KQZ_Card();
            kQZ_Card.CardID = cardID;
            kQZ_Card.EmployeeID = employeeID;
            kQZ_Card.CardTime = cardTime;
            kQZ_Card.CardTypeID = cardTypeID;
            kQZ_Card.DevID = devID;
            kQZ_Card.DevClass = devClass;
            kQZ_Card.ImgID = imgID;
            kQZ_Card.ImgStatus = imgStatus;
            kQZ_Card.IsValidate = isValidate;
            kQZ_Card.FaceIDNo = faceIDNo;
            kQZ_Card.ModifyUser = modifyUser;
            kQZ_Card.ModifyType = modifyType;
            return kQZ_Card;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 CardID
        {
            get
            {
                return _CardID;
            }
            set
            {
                if (_CardID != value)
                {
                    OnCardIDChanging(value);
                    ReportPropertyChanging("CardID");
                    _CardID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CardID");
                    OnCardIDChanged();
                }
            }
        }
        private global::System.Int64 _CardID;
        partial void OnCardIDChanging(global::System.Int64 value);
        partial void OnCardIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 EmployeeID
        {
            get
            {
                return _EmployeeID;
            }
            set
            {
                OnEmployeeIDChanging(value);
                ReportPropertyChanging("EmployeeID");
                _EmployeeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EmployeeID");
                OnEmployeeIDChanged();
            }
        }
        private global::System.Int64 _EmployeeID;
        partial void OnEmployeeIDChanging(global::System.Int64 value);
        partial void OnEmployeeIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CardTime
        {
            get
            {
                return _CardTime;
            }
            set
            {
                OnCardTimeChanging(value);
                ReportPropertyChanging("CardTime");
                _CardTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CardTime");
                OnCardTimeChanged();
            }
        }
        private global::System.DateTime _CardTime;
        partial void OnCardTimeChanging(global::System.DateTime value);
        partial void OnCardTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 CardTypeID
        {
            get
            {
                return _CardTypeID;
            }
            set
            {
                OnCardTypeIDChanging(value);
                ReportPropertyChanging("CardTypeID");
                _CardTypeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CardTypeID");
                OnCardTypeIDChanged();
            }
        }
        private global::System.Int16 _CardTypeID;
        partial void OnCardTypeIDChanging(global::System.Int16 value);
        partial void OnCardTypeIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 DevID
        {
            get
            {
                return _DevID;
            }
            set
            {
                OnDevIDChanging(value);
                ReportPropertyChanging("DevID");
                _DevID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DevID");
                OnDevIDChanged();
            }
        }
        private global::System.Int64 _DevID;
        partial void OnDevIDChanging(global::System.Int64 value);
        partial void OnDevIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 DevClass
        {
            get
            {
                return _DevClass;
            }
            set
            {
                OnDevClassChanging(value);
                ReportPropertyChanging("DevClass");
                _DevClass = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DevClass");
                OnDevClassChanged();
            }
        }
        private global::System.Int16 _DevClass;
        partial void OnDevClassChanging(global::System.Int16 value);
        partial void OnDevClassChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String cVerify
        {
            get
            {
                return _cVerify;
            }
            set
            {
                OncVerifyChanging(value);
                ReportPropertyChanging("cVerify");
                _cVerify = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("cVerify");
                OncVerifyChanged();
            }
        }
        private global::System.String _cVerify;
        partial void OncVerifyChanging(global::System.String value);
        partial void OncVerifyChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ImgID
        {
            get
            {
                return _ImgID;
            }
            set
            {
                OnImgIDChanging(value);
                ReportPropertyChanging("ImgID");
                _ImgID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ImgID");
                OnImgIDChanged();
            }
        }
        private global::System.Int64 _ImgID;
        partial void OnImgIDChanging(global::System.Int64 value);
        partial void OnImgIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 ImgStatus
        {
            get
            {
                return _ImgStatus;
            }
            set
            {
                OnImgStatusChanging(value);
                ReportPropertyChanging("ImgStatus");
                _ImgStatus = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ImgStatus");
                OnImgStatusChanged();
            }
        }
        private global::System.Int16 _ImgStatus;
        partial void OnImgStatusChanging(global::System.Int16 value);
        partial void OnImgStatusChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 IsValidate
        {
            get
            {
                return _IsValidate;
            }
            set
            {
                OnIsValidateChanging(value);
                ReportPropertyChanging("IsValidate");
                _IsValidate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsValidate");
                OnIsValidateChanged();
            }
        }
        private global::System.Int16 _IsValidate;
        partial void OnIsValidateChanging(global::System.Int16 value);
        partial void OnIsValidateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FaceIDNo
        {
            get
            {
                return _FaceIDNo;
            }
            set
            {
                OnFaceIDNoChanging(value);
                ReportPropertyChanging("FaceIDNo");
                _FaceIDNo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FaceIDNo");
                OnFaceIDNoChanged();
            }
        }
        private global::System.String _FaceIDNo;
        partial void OnFaceIDNoChanging(global::System.String value);
        partial void OnFaceIDNoChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ModifyUser
        {
            get
            {
                return _ModifyUser;
            }
            set
            {
                OnModifyUserChanging(value);
                ReportPropertyChanging("ModifyUser");
                _ModifyUser = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifyUser");
                OnModifyUserChanged();
            }
        }
        private global::System.Int32 _ModifyUser;
        partial void OnModifyUserChanging(global::System.Int32 value);
        partial void OnModifyUserChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 ModifyType
        {
            get
            {
                return _ModifyType;
            }
            set
            {
                OnModifyTypeChanging(value);
                ReportPropertyChanging("ModifyType");
                _ModifyType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifyType");
                OnModifyTypeChanged();
            }
        }
        private global::System.Int16 _ModifyType;
        partial void OnModifyTypeChanging(global::System.Int16 value);
        partial void OnModifyTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ModifyTime
        {
            get
            {
                return _ModifyTime;
            }
            set
            {
                OnModifyTimeChanging(value);
                ReportPropertyChanging("ModifyTime");
                _ModifyTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifyTime");
                OnModifyTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _ModifyTime;
        partial void OnModifyTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnModifyTimeChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HWATTModel", Name="KQZ_Employee")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class KQZ_Employee : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 KQZ_Employee 对象。
        /// </summary>
        /// <param name="employeeID">EmployeeID 属性的初始值。</param>
        /// <param name="brchID">BrchID 属性的初始值。</param>
        /// <param name="brchName">BrchName 属性的初始值。</param>
        /// <param name="employeeCode">EmployeeCode 属性的初始值。</param>
        /// <param name="employeeName">EmployeeName 属性的初始值。</param>
        /// <param name="gender">Gender 属性的初始值。</param>
        /// <param name="privilege">Privilege 属性的初始值。</param>
        /// <param name="isCheck">IsCheck 属性的初始值。</param>
        /// <param name="onRule">OnRule 属性的初始值。</param>
        /// <param name="offRule">OffRule 属性的初始值。</param>
        /// <param name="canOvertime">CanOvertime 属性的初始值。</param>
        /// <param name="haveFesta">HaveFesta 属性的初始值。</param>
        /// <param name="devType">DevType 属性的初始值。</param>
        /// <param name="registerType">RegisterType 属性的初始值。</param>
        /// <param name="modelNum">ModelNum 属性的初始值。</param>
        /// <param name="havePwd">HavePwd 属性的初始值。</param>
        public static KQZ_Employee CreateKQZ_Employee(global::System.Int64 employeeID, global::System.Int64 brchID, global::System.String brchName, global::System.String employeeCode, global::System.String employeeName, global::System.Int16 gender, global::System.Int16 privilege, global::System.Int16 isCheck, global::System.Int16 onRule, global::System.Int16 offRule, global::System.Int16 canOvertime, global::System.Int16 haveFesta, global::System.Int16 devType, global::System.Int16 registerType, global::System.Int16 modelNum, global::System.Int16 havePwd)
        {
            KQZ_Employee kQZ_Employee = new KQZ_Employee();
            kQZ_Employee.EmployeeID = employeeID;
            kQZ_Employee.BrchID = brchID;
            kQZ_Employee.BrchName = brchName;
            kQZ_Employee.EmployeeCode = employeeCode;
            kQZ_Employee.EmployeeName = employeeName;
            kQZ_Employee.Gender = gender;
            kQZ_Employee.Privilege = privilege;
            kQZ_Employee.IsCheck = isCheck;
            kQZ_Employee.OnRule = onRule;
            kQZ_Employee.OffRule = offRule;
            kQZ_Employee.CanOvertime = canOvertime;
            kQZ_Employee.HaveFesta = haveFesta;
            kQZ_Employee.DevType = devType;
            kQZ_Employee.RegisterType = registerType;
            kQZ_Employee.ModelNum = modelNum;
            kQZ_Employee.HavePwd = havePwd;
            return kQZ_Employee;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 EmployeeID
        {
            get
            {
                return _EmployeeID;
            }
            set
            {
                if (_EmployeeID != value)
                {
                    OnEmployeeIDChanging(value);
                    ReportPropertyChanging("EmployeeID");
                    _EmployeeID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("EmployeeID");
                    OnEmployeeIDChanged();
                }
            }
        }
        private global::System.Int64 _EmployeeID;
        partial void OnEmployeeIDChanging(global::System.Int64 value);
        partial void OnEmployeeIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 BrchID
        {
            get
            {
                return _BrchID;
            }
            set
            {
                OnBrchIDChanging(value);
                ReportPropertyChanging("BrchID");
                _BrchID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BrchID");
                OnBrchIDChanged();
            }
        }
        private global::System.Int64 _BrchID;
        partial void OnBrchIDChanging(global::System.Int64 value);
        partial void OnBrchIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BrchName
        {
            get
            {
                return _BrchName;
            }
            set
            {
                OnBrchNameChanging(value);
                ReportPropertyChanging("BrchName");
                _BrchName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("BrchName");
                OnBrchNameChanged();
            }
        }
        private global::System.String _BrchName;
        partial void OnBrchNameChanging(global::System.String value);
        partial void OnBrchNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EmployeeCode
        {
            get
            {
                return _EmployeeCode;
            }
            set
            {
                OnEmployeeCodeChanging(value);
                ReportPropertyChanging("EmployeeCode");
                _EmployeeCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EmployeeCode");
                OnEmployeeCodeChanged();
            }
        }
        private global::System.String _EmployeeCode;
        partial void OnEmployeeCodeChanging(global::System.String value);
        partial void OnEmployeeCodeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EmployeeName
        {
            get
            {
                return _EmployeeName;
            }
            set
            {
                OnEmployeeNameChanging(value);
                ReportPropertyChanging("EmployeeName");
                _EmployeeName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EmployeeName");
                OnEmployeeNameChanged();
            }
        }
        private global::System.String _EmployeeName;
        partial void OnEmployeeNameChanging(global::System.String value);
        partial void OnEmployeeNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 Gender
        {
            get
            {
                return _Gender;
            }
            set
            {
                OnGenderChanging(value);
                ReportPropertyChanging("Gender");
                _Gender = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Gender");
                OnGenderChanged();
            }
        }
        private global::System.Int16 _Gender;
        partial void OnGenderChanging(global::System.Int16 value);
        partial void OnGenderChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Birthday
        {
            get
            {
                return _Birthday;
            }
            set
            {
                OnBirthdayChanging(value);
                ReportPropertyChanging("Birthday");
                _Birthday = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Birthday");
                OnBirthdayChanged();
            }
        }
        private Nullable<global::System.DateTime> _Birthday;
        partial void OnBirthdayChanging(Nullable<global::System.DateTime> value);
        partial void OnBirthdayChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nation
        {
            get
            {
                return _Nation;
            }
            set
            {
                OnNationChanging(value);
                ReportPropertyChanging("Nation");
                _Nation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nation");
                OnNationChanged();
            }
        }
        private global::System.String _Nation;
        partial void OnNationChanging(global::System.String value);
        partial void OnNationChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NATIVEPLACE
        {
            get
            {
                return _NATIVEPLACE;
            }
            set
            {
                OnNATIVEPLACEChanging(value);
                ReportPropertyChanging("NATIVEPLACE");
                _NATIVEPLACE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NATIVEPLACE");
                OnNATIVEPLACEChanged();
            }
        }
        private global::System.String _NATIVEPLACE;
        partial void OnNATIVEPLACEChanging(global::System.String value);
        partial void OnNATIVEPLACEChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ZhengZhi
        {
            get
            {
                return _ZhengZhi;
            }
            set
            {
                OnZhengZhiChanging(value);
                ReportPropertyChanging("ZhengZhi");
                _ZhengZhi = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ZhengZhi");
                OnZhengZhiChanged();
            }
        }
        private global::System.String _ZhengZhi;
        partial void OnZhengZhiChanging(global::System.String value);
        partial void OnZhengZhiChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MARITALSTATUS
        {
            get
            {
                return _MARITALSTATUS;
            }
            set
            {
                OnMARITALSTATUSChanging(value);
                ReportPropertyChanging("MARITALSTATUS");
                _MARITALSTATUS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MARITALSTATUS");
                OnMARITALSTATUSChanged();
            }
        }
        private global::System.String _MARITALSTATUS;
        partial void OnMARITALSTATUSChanging(global::System.String value);
        partial void OnMARITALSTATUSChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Health
        {
            get
            {
                return _Health;
            }
            set
            {
                OnHealthChanging(value);
                ReportPropertyChanging("Health");
                _Health = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Health");
                OnHealthChanged();
            }
        }
        private global::System.String _Health;
        partial void OnHealthChanging(global::System.String value);
        partial void OnHealthChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String APOSITION
        {
            get
            {
                return _APOSITION;
            }
            set
            {
                OnAPOSITIONChanging(value);
                ReportPropertyChanging("APOSITION");
                _APOSITION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("APOSITION");
                OnAPOSITIONChanged();
            }
        }
        private global::System.String _APOSITION;
        partial void OnAPOSITIONChanging(global::System.String value);
        partial void OnAPOSITIONChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EDUCATION
        {
            get
            {
                return _EDUCATION;
            }
            set
            {
                OnEDUCATIONChanging(value);
                ReportPropertyChanging("EDUCATION");
                _EDUCATION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EDUCATION");
                OnEDUCATIONChanged();
            }
        }
        private global::System.String _EDUCATION;
        partial void OnEDUCATIONChanging(global::System.String value);
        partial void OnEDUCATIONChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String School
        {
            get
            {
                return _School;
            }
            set
            {
                OnSchoolChanging(value);
                ReportPropertyChanging("School");
                _School = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("School");
                OnSchoolChanged();
            }
        }
        private global::System.String _School;
        partial void OnSchoolChanging(global::System.String value);
        partial void OnSchoolChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Graduation
        {
            get
            {
                return _Graduation;
            }
            set
            {
                OnGraduationChanging(value);
                ReportPropertyChanging("Graduation");
                _Graduation = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Graduation");
                OnGraduationChanged();
            }
        }
        private Nullable<global::System.DateTime> _Graduation;
        partial void OnGraduationChanging(Nullable<global::System.DateTime> value);
        partial void OnGraduationChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String WorkPhone
        {
            get
            {
                return _WorkPhone;
            }
            set
            {
                OnWorkPhoneChanging(value);
                ReportPropertyChanging("WorkPhone");
                _WorkPhone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("WorkPhone");
                OnWorkPhoneChanged();
            }
        }
        private global::System.String _WorkPhone;
        partial void OnWorkPhoneChanging(global::System.String value);
        partial void OnWorkPhoneChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EnrollDate
        {
            get
            {
                return _EnrollDate;
            }
            set
            {
                OnEnrollDateChanging(value);
                ReportPropertyChanging("EnrollDate");
                _EnrollDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EnrollDate");
                OnEnrollDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _EnrollDate;
        partial void OnEnrollDateChanging(Nullable<global::System.DateTime> value);
        partial void OnEnrollDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 Privilege
        {
            get
            {
                return _Privilege;
            }
            set
            {
                OnPrivilegeChanging(value);
                ReportPropertyChanging("Privilege");
                _Privilege = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Privilege");
                OnPrivilegeChanged();
            }
        }
        private global::System.Int16 _Privilege;
        partial void OnPrivilegeChanging(global::System.Int16 value);
        partial void OnPrivilegeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Photo
        {
            get
            {
                return StructuralObject.GetValidValue(_Photo);
            }
            set
            {
                OnPhotoChanging(value);
                ReportPropertyChanging("Photo");
                _Photo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Photo");
                OnPhotoChanged();
            }
        }
        private global::System.Byte[] _Photo;
        partial void OnPhotoChanging(global::System.Byte[] value);
        partial void OnPhotoChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IDCard
        {
            get
            {
                return _IDCard;
            }
            set
            {
                OnIDCardChanging(value);
                ReportPropertyChanging("IDCard");
                _IDCard = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IDCard");
                OnIDCardChanged();
            }
        }
        private global::System.String _IDCard;
        partial void OnIDCardChanging(global::System.String value);
        partial void OnIDCardChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AddrHome
        {
            get
            {
                return _AddrHome;
            }
            set
            {
                OnAddrHomeChanging(value);
                ReportPropertyChanging("AddrHome");
                _AddrHome = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AddrHome");
                OnAddrHomeChanged();
            }
        }
        private global::System.String _AddrHome;
        partial void OnAddrHomeChanging(global::System.String value);
        partial void OnAddrHomeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CardCode
        {
            get
            {
                return _CardCode;
            }
            set
            {
                OnCardCodeChanging(value);
                ReportPropertyChanging("CardCode");
                _CardCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CardCode");
                OnCardCodeChanged();
            }
        }
        private global::System.String _CardCode;
        partial void OnCardCodeChanging(global::System.String value);
        partial void OnCardCodeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Mobile
        {
            get
            {
                return _Mobile;
            }
            set
            {
                OnMobileChanging(value);
                ReportPropertyChanging("Mobile");
                _Mobile = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Mobile");
                OnMobileChanged();
            }
        }
        private global::System.String _Mobile;
        partial void OnMobileChanging(global::System.String value);
        partial void OnMobileChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 IsCheck
        {
            get
            {
                return _IsCheck;
            }
            set
            {
                OnIsCheckChanging(value);
                ReportPropertyChanging("IsCheck");
                _IsCheck = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsCheck");
                OnIsCheckChanged();
            }
        }
        private global::System.Int16 _IsCheck;
        partial void OnIsCheckChanging(global::System.Int16 value);
        partial void OnIsCheckChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 OnRule
        {
            get
            {
                return _OnRule;
            }
            set
            {
                OnOnRuleChanging(value);
                ReportPropertyChanging("OnRule");
                _OnRule = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OnRule");
                OnOnRuleChanged();
            }
        }
        private global::System.Int16 _OnRule;
        partial void OnOnRuleChanging(global::System.Int16 value);
        partial void OnOnRuleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 OffRule
        {
            get
            {
                return _OffRule;
            }
            set
            {
                OnOffRuleChanging(value);
                ReportPropertyChanging("OffRule");
                _OffRule = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OffRule");
                OnOffRuleChanged();
            }
        }
        private global::System.Int16 _OffRule;
        partial void OnOffRuleChanging(global::System.Int16 value);
        partial void OnOffRuleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 CanOvertime
        {
            get
            {
                return _CanOvertime;
            }
            set
            {
                OnCanOvertimeChanging(value);
                ReportPropertyChanging("CanOvertime");
                _CanOvertime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CanOvertime");
                OnCanOvertimeChanged();
            }
        }
        private global::System.Int16 _CanOvertime;
        partial void OnCanOvertimeChanging(global::System.Int16 value);
        partial void OnCanOvertimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 HaveFesta
        {
            get
            {
                return _HaveFesta;
            }
            set
            {
                OnHaveFestaChanging(value);
                ReportPropertyChanging("HaveFesta");
                _HaveFesta = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HaveFesta");
                OnHaveFestaChanged();
            }
        }
        private global::System.Int16 _HaveFesta;
        partial void OnHaveFestaChanging(global::System.Int16 value);
        partial void OnHaveFestaChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 DevType
        {
            get
            {
                return _DevType;
            }
            set
            {
                OnDevTypeChanging(value);
                ReportPropertyChanging("DevType");
                _DevType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DevType");
                OnDevTypeChanged();
            }
        }
        private global::System.Int16 _DevType;
        partial void OnDevTypeChanging(global::System.Int16 value);
        partial void OnDevTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] HDCPInfo
        {
            get
            {
                return StructuralObject.GetValidValue(_HDCPInfo);
            }
            set
            {
                OnHDCPInfoChanging(value);
                ReportPropertyChanging("HDCPInfo");
                _HDCPInfo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HDCPInfo");
                OnHDCPInfoChanged();
            }
        }
        private global::System.Byte[] _HDCPInfo;
        partial void OnHDCPInfoChanging(global::System.Byte[] value);
        partial void OnHDCPInfoChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 RegisterType
        {
            get
            {
                return _RegisterType;
            }
            set
            {
                OnRegisterTypeChanging(value);
                ReportPropertyChanging("RegisterType");
                _RegisterType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RegisterType");
                OnRegisterTypeChanged();
            }
        }
        private global::System.Int16 _RegisterType;
        partial void OnRegisterTypeChanging(global::System.Int16 value);
        partial void OnRegisterTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comment
        {
            get
            {
                return _Comment;
            }
            set
            {
                OnCommentChanging(value);
                ReportPropertyChanging("Comment");
                _Comment = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comment");
                OnCommentChanged();
            }
        }
        private global::System.String _Comment;
        partial void OnCommentChanging(global::System.String value);
        partial void OnCommentChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmployeeLogPwd
        {
            get
            {
                return _EmployeeLogPwd;
            }
            set
            {
                OnEmployeeLogPwdChanging(value);
                ReportPropertyChanging("EmployeeLogPwd");
                _EmployeeLogPwd = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EmployeeLogPwd");
                OnEmployeeLogPwdChanged();
            }
        }
        private global::System.String _EmployeeLogPwd;
        partial void OnEmployeeLogPwdChanging(global::System.String value);
        partial void OnEmployeeLogPwdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CheckType
        {
            get
            {
                return _CheckType;
            }
            set
            {
                OnCheckTypeChanging(value);
                ReportPropertyChanging("CheckType");
                _CheckType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CheckType");
                OnCheckTypeChanged();
            }
        }
        private global::System.String _CheckType;
        partial void OnCheckTypeChanging(global::System.String value);
        partial void OnCheckTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OpendoorType
        {
            get
            {
                return _OpendoorType;
            }
            set
            {
                OnOpendoorTypeChanging(value);
                ReportPropertyChanging("OpendoorType");
                _OpendoorType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OpendoorType");
                OnOpendoorTypeChanged();
            }
        }
        private global::System.String _OpendoorType;
        partial void OnOpendoorTypeChanging(global::System.String value);
        partial void OnOpendoorTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 ModelNum
        {
            get
            {
                return _ModelNum;
            }
            set
            {
                OnModelNumChanging(value);
                ReportPropertyChanging("ModelNum");
                _ModelNum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModelNum");
                OnModelNumChanged();
            }
        }
        private global::System.Int16 _ModelNum;
        partial void OnModelNumChanging(global::System.Int16 value);
        partial void OnModelNumChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 HavePwd
        {
            get
            {
                return _HavePwd;
            }
            set
            {
                OnHavePwdChanging(value);
                ReportPropertyChanging("HavePwd");
                _HavePwd = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HavePwd");
                OnHavePwdChanged();
            }
        }
        private global::System.Int16 _HavePwd;
        partial void OnHavePwdChanging(global::System.Int16 value);
        partial void OnHavePwdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> StaffStatus
        {
            get
            {
                return _StaffStatus;
            }
            set
            {
                OnStaffStatusChanging(value);
                ReportPropertyChanging("StaffStatus");
                _StaffStatus = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StaffStatus");
                OnStaffStatusChanged();
            }
        }
        private Nullable<global::System.Int16> _StaffStatus;
        partial void OnStaffStatusChanging(Nullable<global::System.Int16> value);
        partial void OnStaffStatusChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> LastCardID
        {
            get
            {
                return _LastCardID;
            }
            set
            {
                OnLastCardIDChanging(value);
                ReportPropertyChanging("LastCardID");
                _LastCardID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastCardID");
                OnLastCardIDChanged();
            }
        }
        private Nullable<global::System.Int64> _LastCardID;
        partial void OnLastCardIDChanging(Nullable<global::System.Int64> value);
        partial void OnLastCardIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Reserved1
        {
            get
            {
                return _Reserved1;
            }
            set
            {
                OnReserved1Changing(value);
                ReportPropertyChanging("Reserved1");
                _Reserved1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Reserved1");
                OnReserved1Changed();
            }
        }
        private global::System.String _Reserved1;
        partial void OnReserved1Changing(global::System.String value);
        partial void OnReserved1Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Reserved2
        {
            get
            {
                return _Reserved2;
            }
            set
            {
                OnReserved2Changing(value);
                ReportPropertyChanging("Reserved2");
                _Reserved2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Reserved2");
                OnReserved2Changed();
            }
        }
        private global::System.String _Reserved2;
        partial void OnReserved2Changing(global::System.String value);
        partial void OnReserved2Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Reserved3
        {
            get
            {
                return _Reserved3;
            }
            set
            {
                OnReserved3Changing(value);
                ReportPropertyChanging("Reserved3");
                _Reserved3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Reserved3");
                OnReserved3Changed();
            }
        }
        private global::System.String _Reserved3;
        partial void OnReserved3Changing(global::System.String value);
        partial void OnReserved3Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Reserved4
        {
            get
            {
                return _Reserved4;
            }
            set
            {
                OnReserved4Changing(value);
                ReportPropertyChanging("Reserved4");
                _Reserved4 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Reserved4");
                OnReserved4Changed();
            }
        }
        private global::System.String _Reserved4;
        partial void OnReserved4Changing(global::System.String value);
        partial void OnReserved4Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DEVTYPESTR
        {
            get
            {
                return _DEVTYPESTR;
            }
            set
            {
                OnDEVTYPESTRChanging(value);
                ReportPropertyChanging("DEVTYPESTR");
                _DEVTYPESTR = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DEVTYPESTR");
                OnDEVTYPESTRChanged();
            }
        }
        private global::System.String _DEVTYPESTR;
        partial void OnDEVTYPESTRChanging(global::System.String value);
        partial void OnDEVTYPESTRChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> BEGINATTDATE
        {
            get
            {
                return _BEGINATTDATE;
            }
            set
            {
                OnBEGINATTDATEChanging(value);
                ReportPropertyChanging("BEGINATTDATE");
                _BEGINATTDATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BEGINATTDATE");
                OnBEGINATTDATEChanged();
            }
        }
        private Nullable<global::System.DateTime> _BEGINATTDATE;
        partial void OnBEGINATTDATEChanging(Nullable<global::System.DateTime> value);
        partial void OnBEGINATTDATEChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ENDATTDATE
        {
            get
            {
                return _ENDATTDATE;
            }
            set
            {
                OnENDATTDATEChanging(value);
                ReportPropertyChanging("ENDATTDATE");
                _ENDATTDATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ENDATTDATE");
                OnENDATTDATEChanged();
            }
        }
        private Nullable<global::System.DateTime> _ENDATTDATE;
        partial void OnENDATTDATEChanging(Nullable<global::System.DateTime> value);
        partial void OnENDATTDATEChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RealEmployeeCode
        {
            get
            {
                return _RealEmployeeCode;
            }
            set
            {
                OnRealEmployeeCodeChanging(value);
                ReportPropertyChanging("RealEmployeeCode");
                _RealEmployeeCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RealEmployeeCode");
                OnRealEmployeeCodeChanged();
            }
        }
        private global::System.String _RealEmployeeCode;
        partial void OnRealEmployeeCodeChanging(global::System.String value);
        partial void OnRealEmployeeCodeChanged();

        #endregion
    
    }

    #endregion
    
}
