//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attendance
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance_FeeCalculator
    {
        public int id { get; set; }
        public Nullable<int> Unit { get; set; }
        public Nullable<decimal> UnitFee { get; set; }
        public Nullable<decimal> MaxFee { get; set; }
        public Nullable<int> classId { get; set; }
        public string dateEnum { get; set; }
    }
}
