//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attendance
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance_Scheme
    {
        public Attendance_Scheme()
        {
            this.Attendance_SchemeClass = new HashSet<Attendance_SchemeClass>();
        }
    
        public int schemeID { get; set; }
        public string schemeName { get; set; }
        public string schemeDescription { get; set; }
        public Nullable<int> periods { get; set; }
        public Nullable<int> classs { get; set; }
    
        public virtual ICollection<Attendance_SchemeClass> Attendance_SchemeClass { get; set; }
    }
}
